services:
  admin:
    build: ./admin
    container_name: admin_service
    ports:
      - "3001:3000"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  default:
    driver: bridge

