
version: "3.9"

services:
  admin:
    build: ./admin
    container_name: admin_app
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
